# Generated by Django 4.2.1 on 2023-05-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('positive', models.CharField(max_length=500)),
                ('negative', models.CharField(max_length=500)),
            ],
        ),
    ]
